### ISSUE TITLE
Buttons won't press

### ISSUE THREAD

**Issue by 89jd** [mkorcha/MediaButtonOverlay#1]
Hi

I am having an issue that I can only drag the buttons, I'm unable to click them, they also appear greyed out. This is with the latest store version

**Comment by 89jd** [comment]
Ps. This on a galaxy s8

**Comment by mkorcha** [comment]
Which version of Android are you running?

**Comment by 89jd** [comment]
7.0

**Comment by mkorcha** [comment]
I put an update out yesterday that should help with the issue.
